SELECT LANCAMENTO.DOCUMENTO, LANCAMENTO.DATAVENCIMENTO, LANCAMENTO.PARCELA, CLIENT_FORNEC.NOME AS CLI_FOR,
LANCAMENTO.VALOR, DATAEMISSAO, HISTORICO_OBSERVACAO, CATEGORIA.DESCRICAO AS CATEGORIA
FROM LANCAMENTO
INNER JOIN PESSOA AS CLIENT_FORNEC ON LANCAMENTO.COD_CLIENTE_FORNECEDOR = CLIENT_FORNEC.COD
INNER JOIN PESSOA AS FUNC ON LANCAMENTO.COD_FUNCIONARIO = FUNC.COD
INNER JOIN CONTA_EXTRATO AS CONTA_REC_PAG ON LANCAMENTO.COD_CONTA_EXTRATO = CONTA_REC_PAG.COD
INNER JOIN SUBCATEGORIA ON LANCAMENTO.COD_SUBCATEGORIA = SUBCATEGORIA.COD
INNER JOIN CATEGORIA ON SUBCATEGORIA.COD_CATEGORIA = CATEGORIA.COD

--<td>1</td>
--<td>2021-12-22</td>	
--<td>1/1</td>	
--<td>CLIENTE DE TESTE</td>	
--<td>1000.00</td>	
--<td>2021-11-22</td> 
--<td>00:00:00.000</td>	
--<td>TESTE</td> 
--<td>HISTORICO</td>	
--<td>DESPESA</td>